/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application.Controller;

/**
 *
 * @author acer
 */
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.TableView;
import javafx.scene.input.MouseEvent;

import javafx.scene.layout.BorderPane;

public class EspaceApprennentController implements Initializable {
	@FXML
	private BorderPane bp1;
	@FXML
	private Button Emploitbu;
	@FXML
	private Button Absencebu;
	@FXML
	private Button Notebu;
	@FXML
	private Button CourBuAp;
	@FXML
	private Button Telecharger;
	@FXML
	private Button CompteAppre;
	@FXML
	private Label welcApp;
	@FXML
	private Button Deconnection;
	@FXML
	private Button telech;
	@FXML
	private TableView tableEmpApp;

	// Event Listener on Button[#telech].onAction
	@FXML
	public void telech(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	private Label welcAppre;


	// Event Listener on Button[#Emploitbu].onMouseClicked
	@FXML
	public void Emploitbu(MouseEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#CourBuAp].onMouseClicked
	@FXML
	public void CourBuAp(MouseEvent event) {
		// TODO Autogenerated
	}
	
	
	
	// Event Listener on Button[#Absencebu].onMouseClicked
	@FXML
	public void Absence(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Notebu].onMouseClicked
	@FXML
	public void Note(MouseEvent event) {
		// TODO Autogenerated
	}


	// Event Listener on Button[#CompteAppre].onAction
	@FXML
	public void CompteAppre(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Deconnection].onAction
	@FXML
	public void Deconnection(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
	
	
	


	
	
}

